version: '3'
services:
    apache:
        container_name: apache
        restart: always

    database:
        container_name: mysql
        restart: always

    php-fpm:
        container_name: php-fpm
        restart: always

    php-cli:
        container_name: php-cli
        restart: always

networks:
    app:
