version: '3'
services:
    apache:
        env_file:
            - .env
        depends_on:
            - php-fpm
            - mailhog

    php-fpm:
        env_file:
            - .env

    php-cli:
        env_file:
            - .env

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - 8025:8025
